version: 2.1
orbs:
  jira: circleci/jira@1.3.0
jobs:
  build-react-tests:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Stock and Price App React Tests Image
          path: stockAndPrices/web/stock-and-prices-app
          command: |
            docker build -t stock-and-prices-react-app-tests -f ./docker/stock-and-prices-tests-dockerfile .
      - run:
          name: Run Stock and Prices App React Tests
          path: stockAndPrices/web/stock-and-prices-app
          command: |
            docker run -it --name stock-and-prices-react-app-tests stock-and-prices-react-app-tests
      - jira/notify
  build-flask-tests:
    machine: true
    steps: 
      - checkout
      - run:
          name: Build Stock and Price Flask Tests Image
          path: stockAndPrices/services/app
          command: |
            docker build -t stoc-services-tests -f ./docker/stoc-services-tests-dockerfile .
      - run:
          name: Run Stock and Prices Flask Tests
          path: stockAndPrices/services/app
          command: |
            docker run --name stoc-services-tests stoc-services-tests 
      - jira/notify

workflows:
  react-tests:
    jobs:
      - build-react-tests
  flask-tests:
    jobs:
      - build-flask-tests